# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gemini.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gemini.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgemini.proto\x12\x06gemini\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\" \n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2N\n\rGeminiService\x12=\n\x08Generate\x12\x17.gemini.GenerateRequest\x1a\x18.gemini.GenerateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gemini_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=24
  _globals['_GENERATEREQUEST']._serialized_end=57
  _globals['_GENERATERESPONSE']._serialized_start=59
  _globals['_GENERATERESPONSE']._serialized_end=91
  _globals['_GEMINISERVICE']._serialized_start=93
  _globals['_GEMINISERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
