"""Protocol (interface) for transaction store implementations."""

from typing import Optional, Protocol, runtime_checkable

from storage.schema import Transaction


@runtime_checkable
class TransactionStore(Protocol):
    def insert(self, prompt: str, response: str) -> int: ...
    def query_by_id(self, row_id: int) -> Optional[Transaction]: ...
    def list_all(self) -> list[Transaction]: ...
    def latest(self) -> Optional[Transaction]: ...
    def close(self) -> None: ...
