"""Protocol (interface) for transaction store implementations."""

from typing import Protocol
from typing import runtime_checkable

from storage.schema import Transaction


@runtime_checkable
class TransactionStore(Protocol):
    def insert(self, prompt: str, response: str) -> int: ...
    def query_by_id(self, row_id: int) -> Transaction | None: ...
    def list_all(self) -> list[Transaction]: ...
    def latest(self) -> Transaction | None: ...
    def close(self) -> None: ...
